---
title: "3. Analisis"
format: html
code-fold: true
code-summary: "Mostrar código"
editor: visual
---

```{r}
source("C:/Users/ignac/OneDrive/Documentos/GitHub/COTEC-survey-experiment/0. main.R")

df<-read_parquet("cleandata.parquet")


```

# HARSHNESS MEASURES

## NUMBER OF REPETITIONS

```{r}
namelist<- setdiff(namelist, c("alumno_1_1", "alumno_2_1")) # Eliminar los alumnos de los ejemplos

df1<-df[c("id",namelist)]

dfnrep<-df1 %>% 
  pivot_longer(all_of(namelist)) %>%
  drop_na(value) %>% 
  group_by(id) %>%
  mutate(value=ifelse(value=="repite", 1, 0)) %>% 
  summarise(ha=mean(value, na.rm=T)) %>% 
  ungroup()
```

## AVERAGE DEVIATION

```{r}

df2<-df1 %>% 
  pivot_longer(all_of(namelist)) %>% 
  mutate(value=ifelse(value=="repite", 1, 0)) %>% 
  group_by(name) %>% 
  mutate(tasa_rep=(sum(value, na.rm=T)-value)/(n()-1)  
            ) %>% 
  ungroup()

dfad <-df2 %>% 
  drop_na(value) %>% 
  mutate(diferencia= value-tasa_rep) %>% 
  group_by(id) %>% 
  summarise(hb=mean(diferencia, na.rm=T))
```

## DEVIATION WITH RESPECT TO PREDICTED PROBABILITY

```{r}

df2<-df1 %>% 
  pivot_longer(all_of(namelist), names_to="alumno", values_to="repite") %>% 
  mutate(repite=ifelse(repite=="repite", 1, 0)) %>% 
  drop_na(repite)

df2<-df2 %>% 
  mutate(niño=ifelse(alumno %in% vector_niño,1,0), 
         extranjero=ifelse(alumno %in% vector_extranjero, 1, 0), 
         suspensos=ifelse(alumno%in% vector_suspensos, 1, 0), 
         competencias=ifelse(alumno %in% vector_carencias, 1, 0), 
         absentista=ifelse(alumno %in% vector_absentista, 1, 0), 
         disruptivo=ifelse(alumno %in% vector_expulsion, 1, 0), 
         suma=niño+extranjero+suspensos+competencias+absentista+disruptivo)


modelo<-glm(data=df2, formula= repite ~ niño+ extranjero+ suspensos+ competencias+ absentista+ disruptivo, family=binomial)

df2$preds<-predict(modelo, type="response")

plot.roc(roc(response=df2$repite, df2$preds), print.auc = T)

dfdm<-df2 %>% 
  mutate(diferencia=repite-preds) %>% 
  group_by(id) %>% 
  summarise(hc=mean(diferencia, na.rm=T))
```

## DEVIATION WITH RESPECT TO PREDICTED PROBABILITY IN COMPLETE MODEL

```{r}

df2<-df1 %>% 
  pivot_longer(all_of(namelist), names_to="alumno", values_to="repite") %>% 
  mutate(repite=ifelse(repite=="repite", 1, 0)) %>% 
  drop_na(repite)

df2<-df2 %>% 
  mutate(niño=ifelse(alumno %in% vector_niño,1,0), 
         extranjero=ifelse(alumno %in% vector_extranjero, 1, 0), 
         suspensos=ifelse(alumno%in% vector_suspensos, 1, 0), 
         competencias=ifelse(alumno %in% vector_carencias, 1, 0), 
         absentista=ifelse(alumno %in% vector_absentista, 1, 0), 
         disruptivo=ifelse(alumno %in% vector_expulsion, 1, 0), 
         suma=niño+extranjero+suspensos+competencias+absentista+disruptivo)

df4<- df %>% select(id, primaria, titularidad)

df2<-left_join(df2, df4, by="id")

modelo<-glm(data=df2, formula= repite ~ niño+ extranjero+ suspensos+ competencias+ absentista+ disruptivo + primaria + titularidad, family=binomial)

df2$preds_compl<-predict(modelo, type="response")

plot.roc(roc(response=df2$repite, df2$preds_compl), print.auc = T)

dfdm_comp<-df2 %>% 
  mutate(diferencia=repite-preds_compl) %>% 
  group_by(id) %>% 
  summarise(hd=mean(diferencia, na.rm=T))
```

## Unión

```{r}

df3<-inner_join(dfad, dfdm)
df3<-inner_join(df3, dfnrep)
df3<-inner_join(df3, dfdm_comp)

GGally::ggpairs(df3[, c("ha","hb","hc", "hd")])

dfanalisis<- left_join(df3, df)

dfanalisis %>% 
  pivot_longer(cols=c("ha", "hb", "hc", "hd")) %>% 
  group_by(edad, name) %>% 
  summarise(value=mean(value, na.rm=T)) %>% 
  ungroup() %>% 
  ggplot(aes(edad, value, color=name))+
  geom_point()
  
```

# CHARACTERIZING THE TEACHERS

```{r}
dfanalisis <-dfanalisis %>% 
  mutate(indefinido= ifelse(sitlabpub %in% c("Contratada/o laboral indefinido", "Funcionaria/o con destino definitivo"), "indefinido", "temporal"), 
         impacto_estudiantes= ifelse(is.na(impacto_centro_estudiantes), impacto_region_estudiantes, impacto_centro_estudiantes), 
         empatia= case_when(!is.na(empatia_escala_1a5)~ empatia_escala_1a5, 
                            !is.na(empatia_escala_0a100_t1) ~ ceiling(empatia_escala_0a100_t1/20), 
                            !is.na(empatia_escala_0a100_t2) ~ ceiling(empatia_escala_0a100_t2/20), 
                            !is.na(empatia_escala_0a100_t3) ~ ceiling(empatia_escala_0a100_t3/20), 
                            TRUE ~ NA
                            ), 
         empatia= ifelse(empatia==0, 1, empatia)
         )



set.seed(123)

modelo_rf <- ranger(
  formula = hc ~ nivel + experiencia + antiguedad3 + female + edad +
    titularidad + indefinido + grupos_docencia + impacto_estudiantes +
    empatia ,
  data = dfanalisis,
  importance = "permutation",  # mejor que "impurity" en regresión
  num.trees = 1000,
  mtry = 3,        # número de variables candidatas en cada split
  min.node.size = 5, # tamaño mínimo de nodo terminal
  respect.unordered.factors = TRUE
)

df_importancia <- data.frame(
  variable = names(modelo_rf$variable.importance),
  importancia = modelo_rf$variable.importance
) %>%
  arrange(desc(importancia))


modelo_rf2 <- ranger(
  formula = hc ~ nivel + experiencia + antiguedad3 + female + edad +
    titularidad + indefinido + grupos_docencia + impacto_estudiantes +
    empatia + meritocracia,
  data = dfanalisis,
  importance = "permutation",  # mejor que "impurity" en regresión
  num.trees = 1000,
  mtry = 3,        # número de variables candidatas en cada split
  min.node.size = 5, # tamaño mínimo de nodo terminal
  respect.unordered.factors = TRUE
)

df_importancia2 <- data.frame(
  variable = names(modelo_rf2$variable.importance),
  importancia2 = modelo_rf2$variable.importance
) %>%
  arrange(desc(importancia2))

dfimportancia<-full_join(df_importancia, df_importancia2) %>% 
  pivot_longer(cols = c("importancia", "importancia2"))

dfimportancia %>% 
ggplot(aes(x = reorder(variable, value), y = value, fill=name)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(
    title = "Importancia de variables en Random Forest",
    x = "Variable",
    y = "Importancia (permutación)"
  ) +
  theme_minimal()+
  scale_fill_manual(values = c("steelblue", "pink"))
```

```{r}

dfanalisis$pred_rf <- predict(modelo_rf, data = dfanalisis)$predictions
dfanalisis$pred_rf2 <- predict(modelo_rf2, data = dfanalisis)$predictions

dfanalisis %>% 
  select("hc", "pred_rf", "pred_rf2") %>% 
  pivot_longer(cols = c("pred_rf", "pred_rf2")) %>% 
  ggplot(aes(x = hc, y = value, color=name)) +
  geom_point(alpha = 0.6) +
  labs(x = "Observado (ha)", y = "Predicho (Random Forest)") +
    scale_fill_manual(values = c("steelblue", "pink"))

```

```{r}


modeloa<-lm(data=dfanalisis, formula = ha ~ nivel + experiencia + antiguedad3 + female + edad +
          titularidad + indefinido + grupos_docencia + impacto_estudiantes +
          empatia )
modelob<-lm(data=dfanalisis, formula = hb ~ nivel + experiencia + antiguedad3 + female + edad +
              titularidad + indefinido + grupos_docencia + impacto_estudiantes +
              empatia )
modeloc<-lm(data=dfanalisis, formula = hc ~ nivel + experiencia + antiguedad3 + female + edad +
              titularidad + indefinido + grupos_docencia + impacto_estudiantes +
              empatia )
modelod<-lm(data=dfanalisis, formula = hd ~ nivel + experiencia + antiguedad3 + female + edad +
              titularidad + indefinido + grupos_docencia + impacto_estudiantes +
              empatia )


modelsummary::modelsummary(models = list(modeloa, modelob, modeloc, modelod),
                           stars=c("*"=.1, "**"=.05, "***"=.01),
                           include.rsquared = FALSE,
                           include.adjrs = FALSE,
                           include.nobs = FALSE,
                           include.rmse = FALSE)
```

```{r}


modeloa2<-lm(data=dfanalisis, formula = ha ~ nivel + experiencia + antiguedad3 + female + edad + 
              titularidad + indefinido + grupos_docencia + impacto_estudiantes +
              empatia + meritocracia)
modelob2<-lm(data=dfanalisis, formula = hb ~ nivel + experiencia + antiguedad3 + female + edad + 
              titularidad + indefinido + grupos_docencia + impacto_estudiantes +
              empatia + meritocracia)
modeloc2<-lm(data=dfanalisis, formula = hc ~ nivel + experiencia + antiguedad3 + female + edad +
              titularidad + indefinido + grupos_docencia + impacto_estudiantes +
              empatia + meritocracia)
modelod2<-lm(data=dfanalisis, formula = hd ~ nivel + experiencia + antiguedad3 + female + edad + 
              titularidad + indefinido + grupos_docencia + impacto_estudiantes +
              empatia + meritocracia)


modelsummary(models = list(modeloa2, modelob2, modeloc2, modelod2),
                           stars=c("*"=.1, "**"=.05, "***"=.01),
                           include.rsquared = FALSE,
                           include.adjrs = FALSE,
                           include.nobs = FALSE,
                           include.rmse = FALSE)

```

```{r}

dfanalisis %>% 
  group_by(edad) %>% 
  summarise(value=mean(hc, na.rm=T)) %>% 
  ggplot(aes(edad, value))+
  geom_point()
```

# HYPOTHESES

## STUDY I

### H11

```{r}
dfanalisis<-dfanalisis %>% 
  mutate(control=ifelse(treatment==1, 1, 0))

modeloh11a<- lm(data=dfanalisis, formula= ha ~ control)

modelsummary(models = modeloh11a,
             stars=c("*"=.1, "**"=.05, "***"=.01),
             include.rsquared = FALSE,
             include.adjrs = FALSE,
             include.nobs = FALSE,
             include.rmse = FALSE)



```

### H12

```{r}

dfanalisis<-dfanalisis %>% 
  mutate(control=ifelse(treatment==1, 1, 0))

modeloh11a<- lm(data=dfanalisis, formula= ha ~ control)

modelsummary(models = modeloh11a,
             stars=c("*"=.1, "**"=.05, "***"=.01),
             include.rsquared = FALSE,
             include.adjrs = FALSE,
             include.nobs = FALSE,
             include.rmse = FALSE)

```

```{r}
dfanalisis %>% 
  mutate(
    # Crear cortes
    x_cut = cut(
      hb, 
      breaks = seq(-1, 1, by = 0.05),
      include.lowest = TRUE,
      right = FALSE
    ),
    # Convertir cada corte en el punto medio del intervalo
    x = as.numeric(sub("\\((.+),.*", "\\1", sub("\\[|\\)", "", x_cut))) + 0.025
  ) %>% 
  group_by(x) %>% 
  summarise(alumnos= mean(pct_culpa_alumnos, na.rm=T),
            familias= mean(pct_culpa_familias, na.rm=T), 
            profesorado= mean(pct_culpa_profesorado, na.rm=T), 
            sistema= mean(pct_culpa_sistema_educativo, na.rm=T)) %>% 
  pivot_longer(cols = c("alumnos", "familias", "profesorado", "sistema")) %>% 
  ggplot(aes(x, value ,color=name))+
  geom_point()+
  geom_hline(yintercept = 25)

dfanalisis %>% 
  mutate(
    x = floor(hb / 0.1) * 0.1   # redondea hacia arriba al múltiplo más cercano de 0.05
  ) %>% 
  group_by(x) %>% 
  summarise(
    alumnos = mean(pct_culpa_alumnos, na.rm = TRUE),
    familias = mean(pct_culpa_familias, na.rm = TRUE), 
    profesorado = mean(pct_culpa_profesorado, na.rm = TRUE), 
    sistema = mean(pct_culpa_sistema_educativo, na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  pivot_longer(cols = c("alumnos", "familias", "profesorado", "sistema")) %>% 
  ggplot(aes(x, value, color = name)) +
  geom_line() +
  geom_hline(yintercept = 25, linetype = "dashed")
  

dfanalisis %>% 
  ggplot(aes(hb, pct_culpa_familias))+
  geom_point()+
  geom_smooth(
    method = "lm",
    formula = y ~ poly(x, 2),   # polinomio de grado 2
    se = TRUE,                  # intervalo de confianza
    color = "red"
  )


dfanalisis<-dfanalisis %>% 
  mutate(alumno2= pct_culpa_alumnos^2, 
         familias2= pct_culpa_familias^2, 
         profesorado2= pct_culpa_profesorado^2, 
         sistema2= pct_culpa_sistema_educativo^2
  )

summary(lm(data=dfanalisis, formula= hb ~ pct_culpa_profesorado )) # si le restas 25 es diferencia con respecto a 1/4

modalu<-lm(data=dfanalisis, formula =  hb ~ pct_culpa_alumnos)
modfam<-lm(data=dfanalisis, formula = hb ~ pct_culpa_familias)
modprof<-lm(data=dfanalisis, formula =  hb ~ pct_culpa_profesorado)
modsist<-lm(data=dfanalisis, formula = hb ~ pct_culpa_sistema_educativo)

dfanalisisrec<-dfanalisis %>% drop_na(hb, pct_culpa_alumnos)

dfanalisisrec$pred_alumno<-predict(modalu)
dfanalisisrec$pred_fam<-predict(modfam, type="response")
dfanalisisrec$pred_prof<-predict(modprof, type="response")
dfanalisisrec$pred_sist<-predict(modsist, type="response")

dfanalisisrec %>% 
  pivot_longer(cols = c("pred_alumno", "pred_fam", "pred_prof", "pred_sist")) %>% 
  ggplot(aes(hb, value, color=name))+
  geom_line()



dfanalisis %>% 
  ggplot(aes(x= hb))+
  geom_density(smooth=1)+
  geom_vline(xintercept = mean(dfanalisis$hb, na.rm=T), color="red")+
  geom_vline(xintercept = median(dfanalisis$hb, na.rm=T), color="blue")


```
